### ISSUE TITLE
[BUG] Support for Ultrawide missing

### ISSUE THREAD

**Issue by exen904** [hmlendea/gfn-electron#206] opened 2023-09-25 17:19 UTC
### Describe the bug

Not sure if this is really a bug so to speak, but also with this client, I dont get the ultrawide resolution as a choice. Maximum resolution I can pick is 1920x1200.
The account has a Ultimate subscription and on the native windows client it works as expected. 

### To Reproduce

- open settings
- try to change resolution
- max resolution is 1920x1200

### Screenshots

![image](https://github.com/hmlendea/gfn-electron/assets/59537420/482da1a1-4d15-4b3b-8665-9586620aff2b)

### Operating System

EndeavourOS

### Desktop Environment

i3

### Display Server

X11

### Installation method

flatpak

### Version

1.13.0

### Is this a fresh install of the app or an update from a past version?

fresh install

### Did this issue appear right away upon installation/updating, or spontaneously?

right away

### Additional context

flatpak info io.github.hmlendea.geforcenow-electron 

GeForce NOW Electron - Unofficial GeForce NOW application written in Electron

          ID: io.github.hmlendea.geforcenow-electron
         Ref: app/io.github.hmlendea.geforcenow-electron/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.13.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 245,5 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 36fd0f6cbd88ffedf1ed57584da8fd5232b2652e727875054c7877c434ac4a05
      Parent: 1aa9c2e15cb5a7616fbaa5db96a2a7ed27843ce11d2a9a2247c298fa71b29fb4
     Subject: Update geforcenow-electron_1.12.0_linux.zip to 1.13.0 (36544cbe)
        Date: 2023-08-11 13:39:16 +0000

**Comment by ilyearer** [comment] 2023-10-03 02:43
Someone correct me if I'm wrong, but this is a limitation of the Geforce Now website, which gfn-electron is using. This isn't a bug, but by design from Nvidia.

From gfn-electron's disclaimer section:

> It is simply an Electron wrapper that loads the official GFN web application page, just as it would in a regular web browser.

You'll notice that ultrawide support is there, just at 1620x720.

**Comment by hmlendea** [comment] 2023-10-03 08:03
Hi. Yes this is a limitation from Nvidia itself, ѕo І՝m going to have to close this as invalid.

**Closed by hmlendea** 2023-10-03 08:03 UTC
Labels: bug

**Comment by hmlendea** [comment] 2023-10-03 08:41
That's probably possible. However, I did try integrating UA manipulation in this webapp previously, and it was not very successful, as it tends to only work for a while before Nvidia comes up with new ways of detecting the real UA and rendering our hacks obsolete.

Even now there are many open issues regarding those UA hacks that don't work. And I'm kind of leaning towards dropping them entirely, as not only they are very high maintenance (and ultimately, still unreliable), but also because if it's Nvidia's wish to put those limitations in place, I'm not entirely comfortable circumventing them as GFN is their product, and I'm already pushing the limits with this project, I don't want to infringe on their turf and have legal trouble.

**Comment by exen904** [comment] 2023-10-03 11:16
No worries, that's completely fine. I don't think that's the right way to produce that much more workload for the UA manipulation on your side. 
I would maybe however, make a note in the description that UW support probably won't work until NVIDIA changes something. Can report back if they finally decide to fully support it :)

**Comment by Tealk** [comment] 2024-09-13 17:55
So if I read this correctly, the Ultimate membership can do this, but there is still no choice.
https://www.nvidia.com/de-de/geforce-now/system-reqs/
