### ISSUE TITLE
[BUG] Blank screen when trying to connect any store accounts

### ISSUE THREAD

**Issue by SimonMossmyr** [hmlendea/gfn-electron#175] opened 2022-11-24 20:36 UTC
### Describe the bug

The pages for connecting Steam, Epic Games or Ubisoft are entirely blank.

First page:
![image](https://user-images.githubusercontent.com/19503193/203859326-3e214889-8812-459c-800b-462afa61657b.png)

"Connect your store accounts" page:
![image](https://user-images.githubusercontent.com/19503193/203859344-df64917a-9091-4090-ae8f-4a2237d316f5.png)

After clicking any of the "Connect" buttons for Ubisoft, Epic Games or Steam:
![image](https://user-images.githubusercontent.com/19503193/203859356-09744ece-96fb-429a-a00c-16eb594d483f.png)

# Terminal output
```
$ geforcenow-electron 2>&1
Using user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.101 Safari/537.36
Process arguments: /snap/geforcenow-electron/17/geforcenow-electron,--no-sandbox

(geforcenow-electron:8154): Gtk-WARNING **: 21:27:44.077: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(geforcenow-electron:8154): Gtk-WARNING **: 21:27:44.079: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(geforcenow-electron:8154): Gtk-WARNING **: 21:27:44.080: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
(node:8154) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/snap/geforcenow-electron/17/resources/app/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:642:26)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
(Use `geforcenow-electron --trace-warnings ...` to show where the warning was created)
(node:8154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[8154:1124/212744.812441:ERROR:udev_watcher.cc(98)] Failed to begin udev enumeration.
[8154:1124/212744.844167:ERROR:udev_watcher.cc(98)] Failed to begin udev enumeration.
(electron) The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
```

### To Reproduce

1.  Install using Snap
    ```
    $ sudo apt update
    $ sudo apt install snapd
    $ sudo snap install core
    $ sudo snap install geforcenow-electron
    ```
2. Run
3. Log in
4. Click "Connect your store accounts"
5. Click "Connect" for Ubisoft, Epic Games or Steam

### Operating System

Ubuntu 22.04.1 LTS

### Desktop Environment

GNOME 42.4

### Display Server

X11

### Installation method

Snap

### Version

1.10.0

### Is this a fresh install of the app or an update from a past version?

Fresh

### Did this issue appear right away upon installation/updating, or spontaneously?

Yes, right after installation

**Comment by SimonMossmyr** [comment] 2022-11-24 21:06
You can work around this issue by opening GeForce now in a chrome browser https://play.geforcenow.com and adding your store accounts there.

**Comment by mestrini** [comment] 2022-12-08 19:48
I can confirm this using the AppImage. Yesterday was working fine but as of today Nvidia must no longer support non-synced accounts since it forces me to connect the Epic account.
At first I thought it to be a matter of not having the latest version - was using 1.8 - but even with the 1.10 I get the black screen upon account connection.

**Comment by dubfib** [comment] 2022-12-18 16:09
huh, looks like maybe discord-rpc is trying to connect and its failing because it can't find discord

**Comment by jjardon** [comment] 2022-12-30 22:38
I can reproduce this in the flatpak build as well

**Comment by hmlendea** [comment] 2023-06-11 12:29
Closed as this is an issue reported for the `snap` version, which was dropped in #191.

If the issue still exists and is present for the other supported packaging formats, please open a new issue.

**Closed by hmlendea** 2023-06-11 12:29 UTC
Labels: bug
