### ISSUE TITLE
Unable to sign in using Google authentication

### ISSUE THREAD

**Issue by AskInward** [hmlendea/gfn-electron#177] opened 2023-01-02 21:04 UTC
Getting the following error when signing in using google account
![image](https://user-images.githubusercontent.com/24255493/210277878-492f8ba5-fa09-4fe5-8ab7-ec5687e6d9b8.png)

**Comment by YouriyPaluch** [comment] 2023-01-03 09:44
I have this bag too

**Comment by danfitzgerald** [comment] 2023-01-10 03:49
Take a look at issue #49. Looks like its an issue with using electron to sign in instead of the users default browser. You can also read more about it here:

[Upcoming security changes to Google's OAuth 2.0 authorization endpoint in embedded webviews](https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html)

**Comment by hmlendea** [comment] 2023-06-07 14:35
Cloased as duplicate of #49

**Closed by hmlendea** 2023-06-07 14:35 UTC
