### ISSUE TITLE
[BUG] This browser or app may not be secure.

### ISSUE THREAD

**Issue by Skullfurious** [hmlendea/gfn-electron#161] opened 2022-08-10 23:14 UTC
### Describe the bug

When trying to sign in through Google Login the login is halted with the following message:

```
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.
```

Any workarounds currently known for this problem? I have a 6 month subscription on that account so it's not exactly like I can just start up a new account.

### To Reproduce

1) Log in.
2) Sign in with google.
3) Type email.
4) Message as listed above will be displayed.

### Operating System

Pop!_OS

### Desktop Environment

Gnome 42.2

### Display Server

X11

### Installation method

Flatpak

### Version

1.8

### Is this a fresh install of the app or an update from a past version?

Fresh install of 22.04 a few months old now though.

### Did this issue appear right away upon installation/updating, or spontaneously?

Installation.

### Additional context

Found this on google's support pages.

```
To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.

Important: This deadline does not apply to Google Workspace or Google Cloud Identity customers. The enforcement date for these customers will be announced on the Workspace blog at a later date.
```

**Comment by Skullfurious** [comment] 2022-08-10 23:22
This problem will exist more than likely until the Electron version is updated for linux to support the new login methods as far as I can tell.

I was able to work around this by logging in to my NVIDIA account through google (On my chrome browser), and going into my security settings and adding a password to my account manually.

**Comment by hmlendea** [comment] 2022-08-12 05:00
Hi.

Duplicate of #49 

As you have already found out, the only workaround that does not violate Google's ToS and endanger your account, is to set a password and log in traditionally rather than with Google.

It's unfortunate that Google becomes more and more a "walled garden", but it's their choice and we cannot change that.

**Closed by hmlendea** 2022-08-12 05:00 UTC
Labels: bug
