### ISSUE TITLE
[BUG]cant login to google

### ISSUE THREAD

**Issue by manoflinux** [hmlendea/gfn-electron#173] opened 2022-10-10 02:46 UTC
### Describe the bug

click login, click google, enter your email, and click next, and you get this. "Couldn’t sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.
[Help](https://support.google.com/accounts?hl=en&p=account_iph)[Privacy](https://accounts.google.com/TOS?loc=US&hl=en&privacy=true)[Terms](https://accounts.google.com/TOS?loc=US&hl=en)"

### To Reproduce

1. click login
2. click google
3. enter your email 
4. click next

### Screenshots

![image](https://user-images.githubusercontent.com/6595620/194792704-9750a667-9d47-4de2-aa6f-c0cc11b26262.png)

### Operating System

linux 5.x kernel.

### Desktop Environment

tde

### Display Server

x11

### Installation method

appimage

### Version

v1.10.0

### Is this a fresh install of the app or an update from a past version?

fresh

### Did this issue appear right away upon installation/updating, or spontaneously?

solid error

**Comment by hmlendea** [comment] 2022-10-10 10:36
Duplicate of #49

**Closed by hmlendea** 2022-10-10 10:36 UTC
Labels: bug
